# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs", "python3"]

[phases.install]
cmds = [
  "cd backend",
  "npm install --production"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && node src/server.js"
