# Railway Multi-Service Configuration
# This file tells Railway how to deploy both backend and frontend

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
