# Render Blueprint Configuration
# See: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: video-call-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false

  - type: web
    name: video-call-frontend
    runtime: static
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://video-call-backend.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://video-call-backend.onrender.com
