# Render Blueprint - Video Call Application
# Deploys backend and frontend as separate services

services:
  # Backend Service
  - type: web
    name: video-call-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: USE_REDIS
        value: false

  # Frontend Service
  - type: web
    name: video-call-frontend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm install -g serve && serve -s build -l 3000
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: video-call-backend
          property: host
      - key: REACT_APP_SOCKET_URL
        fromService:
          type: web
          name: video-call-backend
          property: host
