# Render Blueprint for Video Call Application
# This file deploys both backend and frontend to Render

services:
  # Backend Service (Node.js API + Socket.IO)
  - type: web
    name: video-call-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: USE_REDIS
        value: false
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: video-call-frontend
          property: host
    healthCheckPath: /health

  # Frontend Service (React) - served as static site
  - type: web
    name: video-call-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: video-call-backend
          property: host
      - key: REACT_APP_SOCKET_URL
        fromService:
          type: web
          name: video-call-backend
          property: host
