# Railway Backend Configuration
[build]
builder = "NIXPACKS"

[build.env]
NODE_ENV = "production"

[deploy]
startCommand = "node src/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/api/video-call/health"
timeout = 30

[deploy.env]
NODE_ENV = "production"
